[tools]
lefthook = "latest"
node = "lts"

[deps.pnpm]
auto = true

[deps.lefthook]
sources = ["lefthook.yml"]
outputs = [".git/hooks/"]
run = "lefthook install"
auto = true
description = "Setup lefthook"

[settings]
lockfile = true

[settings.node]
corepack = true
